### ISSUE TITLE
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 24 bytes) 

### ISSUE THREAD

**Issue by guillermofr** [kasperisager/vanilla-api#41]
Hi, i have a problem when i try to create a new category. (POST /categories)

When I do the CURL call to my localhost, i get this:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 24 bytes) in D:\Guillermo\GIT\xxxxxxxxx\library\core\class.dispatcher.php on line 608

xxxxxx is the name of the proyect

any ideas? , i try increasing the memory limit, but no matter how much i set, all is used...

I dont have any problem with GET calls

**Comment by kasperisager** [comment]
Closing this as an environment specific issue.
