### ISSUE TITLE
More indepth documentation for your API avail somewhere (especially search call)?

### ISSUE THREAD

**Issue by eitzenbe** [kasperisager/vanilla-api#42]
Hi Kasper,

EXCELLENT stuff you've done...
I would like to integrate vanilla to my website using your api and have user synced via calls to create and delete users acccordingly... 

But it was troublesome to collect all sorts of infos from all around the web to get it running...

Is there any indepth documentation about your API avail? like how to specify the search string in the search call e.g.

Kudos and all the best
Thomas

**Comment by kasperisager** [comment]
Glad you like the application! You can find in-depth documentation on configuration, available endpoints, authentication, and extension in the wiki: https://github.com/kasperisager/vanilla-api/wiki

**Comment by eitzenbe** [comment]
Hi Speedy Gonzales ;)

I am aware of this page, but the search call is not clear to me at least 
not with the few lines shown there.
Questions at hand would be: How can I search only specific discussions 
or search for users with a given name or email....

Another topic: The user creation call returns an error about not able to 
instantiate mail sending app. Is there any way to NOT send mails to 
users when being created? and would an errorless call flow return the 
user id in the response?

Off to sleep now, bye bye

br
Thomas

Am 2015-01-27 um 20:25 schrieb Kasper Isager:
>
> Glad you like the application! You can find in-depth documentation on 
> configuration, available endpoints, authentication, and extension in 
> the wiki: https://github.com/kasperisager/vanilla-api/wiki
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kasperisager/vanilla-api/issues/42#issuecomment-71710614>.
>

-- 

Crimes against Nature are Crimes
against Peace and Humanity.
Protect our natural home.
https://www.endecocide.org

**Comment by kasperisager** [comment]
Vanilla only allows simple keyword search out of the box so there's no way to search specific discussions or by other criteria such as names and emails.

As for the user creation endpoint it sounds like you might have a mail configuration issue. The specific error you're receiving has been discussed a least a couple of times on vf.org if I recall correctly. A successful call will return a `User` object that should contain the user ID as well as a bunch of other meta. Vanilla's models aren't exactly trivial so I've left out a lot of the return data in the endpoint documentation and instead simply show empty objects and arrays when a lot of data is expected.

**Comment by tantita** [comment]
Hi @kasperisager , thanks alot for the API, please how can I search for all discussions in a particular category
