### ISSUE TITLE
Which version of Vanilla to use with your API

### ISSUE THREAD

**Issue by eitzenbe** [kasperisager/vanilla-api#43]
Hi Kasper,

I have downloaded and installed the develop branch and enabled your API (0.3.0), however on calling post methods it gets into an infinite loop of dispatch calls

[Wed Jan 28 22:44:00.282126 2015] [:error] [pid 20465] [client 127.0.0.1:38676] PHP  89. Gdn_Dispatcher->Dispatch() /srv/eci-mgt/vanilla/library/core/class.dispatcher.php:372                                                                                                                                              
And what really makes me curious:

To resolve this it helps to create a category via the dashboard :(

Any clue what might cause this? Or which branch / version of vanilla are you proposing to use best with your api?

br
Thomas

PS: Its kinda reproducable....

**Comment by kasperisager** [comment]
I'm testing the application against the current Vanilla `master` and would recommend running it on this as well.

**Comment by alexcroox** [comment]
Is there an API for the current stable release?

**Comment by kasperisager** [comment]
For the current stable release you can use the built-in API. My API shim merely maps the default API to more REST-like URIs.

**Comment by alexcroox** [comment]
Ah I see, is it this one? http://blog.vanillaforums.com/api/ as I /api/v1 on my install doesn't do anything. Sorry, perhaps the wrong place to be asking questions like this :)

**Comment by kasperisager** [comment]
Those are the API docs for the hosted version of Vanilla. Out of the box you can append either `.json` or `.xml` to endpoints to change the response format of controllers. An example would be `http://your-site.com/discussions.json`.

**Comment by alexcroox** [comment]
Ah handy thanks! I'll stick to querying the DB directly until 2.2 reaches stable. Thank you for your help and looking forward to trying this in the future!
