### ISSUE TITLE
Depends on PHP 5.4?

### ISSUE THREAD

**Issue by pavsid** [kasperisager/vanilla-api#46]
Hi, I noticed that the settings/about.php file contains shorthand array syntax which was only introduced in PHP 5.4.

As Vanilla 2.1 supports 5.2 and 2.2 supports 5.3, then shouldn't this plugin also support those versions of PHP?

**Comment by kasperisager** [comment]
In a perfect world, yes, the app should indeed support the same version of PHP as Vanilla. I am however incredibly lazy and have a deep dislike of the long-hand array syntax so PHP 5.3 support won't happen I'm afraid :smile:
