### ISSUE TITLE
Bonked when uploaded to server

### ISSUE THREAD

**Issue by JamesMercury** [kasperisager/vanilla-api#47]
Hello. Much thanks again Kasper for the time you took out to develop this application. 
I keep getting bonked (blank browser window) whenever I upload the application files onto my server. I am using the Vanilla Master(2.2) downloaded from https://github.com/vanilla/vanilla. I also changed the folder name to 'api' on my server. Please help

**Comment by kasperisager** [comment]
You will need to enable debug mode and post whatever error messages pop up here.

**Comment by JamesMercury** [comment]
PHP Parse error:  syntax error, unexpected '[' in /home1/jamesmer/public_html/applications/api/settings/about.php on line 3

(The above was gotten from error_log file from server. I looked scanned about.php and couldn't see any syntactitcal errors...What do you think?)

<?php
//about.php
$ApplicationInfo['api'] = [
    'Name'        => 'API',
    'Description' => 'Extensible RESTful API shim that operates in JSON or XML. Supports JSONP and CORS',
    'Version'     => '0.4.0',
    'Url'         => 'https://github.com/kasperisager/vanilla-api',
    'Author'      => 'Kasper Kronborg Isager',
    'AuthorEmail' => 'kasperisager@gmail.com',
    'AuthorUrl'   => 'https://github.com/kasperisager',
    'License'     => 'MIT',
    'SettingsUrl' => 'dashboard/settings/api',
    'RequiredApplications' => ['Vanilla' => '2.2.x']
];

**Comment by kasperisager** [comment]
Ah, PHP 5.4 is required to use the app.

**Comment by JamesMercury** [comment]
:) Golly gee! Just I just updated to PHP 5.4 and no more bonk. Much thanks!

**Comment by kasperisager** [comment]
No problem!
