### ISSUE TITLE
"Something wrong" happens on enable

### ISSUE THREAD

**Issue by xDaizu** [kasperisager/vanilla-api#48]
So... I've repeated this process 4 or 5 times just to make sure. I download either Vanilla Forums [2.2.3.4](https://github.com/vanilla/vanilla/tree/Vanilla_2.2.3.4) or [Vanilla Forums 2.2.3.6](https://github.com/vanilla/vanilla/tree/Vanilla_2.2.3.6), install it, download api 0.4.0, copy it, open the admin dashboard, enable api application and BAM! "Something has gone wrong." Forum unusable forever. Repeat.

EDIT: Managed to get a backtrace:

**Call to unknown method 'Gdn_Request->requestUri'**
The error occurred on or near: D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.request.php

    128:          $PassedArg = (is_array($Args) && sizeof($Args)) ? $Args[0] : NULL;
    129:          return $this->_EnvironmentElement(strtoupper($Matches[2]),$PassedArg);
    130:       }
    131:       else {
    132:          trigger_error("Call to unknown method 'Gdn_Request->{$Method}'", E_USER_ERROR);
    133:       }
    134:    }
    135: 
    136:    /**

Backtrace:

    D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.request.phpPHP::Gdn_ErrorHandler();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.request.php:132] PHP::trigger_error();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\applications\api\library\class.apiengine.php:304] Gdn_Request->__call();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\applications\api\library\class.apiengine.php:304] Gdn_Request->requestUri();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\applications\api\settings\class.hooks.php:57] APIEngine::getRequestUri();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.pluginmanager.php:724] APIHooks->Gdn_Dispatcher_beforeDispatch_handler();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.pluginmanager.php:657] Gdn_PluginManager->CallEventHandler();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.pluggable.php:144] Gdn_PluginManager->CallEventHandlers();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\library\core\class.dispatcher.php:189] Gdn_Pluggable->FireEvent();
    [D:\xampp\htdocs\vanilla-Vanilla_2.2.3.4\index.php:46] Gdn_Dispatcher->Dispatch();

Variables in local scope:

    [Method] 'requestUri'
    [Args] array (
    )    
    [Matches] array (
     )

**Comment by kasperisager** [comment]
Discussed in #49.
