### ISSUE TITLE
404 on latest Vanilla

### ISSUE THREAD

**Issue by glebb** [kasperisager/vanilla-api#50]
Just did a fresh install on latest Vanilla / master branch. The api endpoints give 404 errors, the admin side looks fine though. Api installed in applications/api.

**Comment by kasperisager** [comment]
Everything's fine on my end on the latest `master` (vanilla/vanilla@054707aef5ec71507935fa71760ee394eaa45c5e). Which endpoint are you trying to access?

**Comment by glebb** [comment]
/api/categories for example. I guess the problem is on my end then. Any ideas?

**Comment by kasperisager** [comment]
Did you enable the application in the dashboard?

**Comment by glebb** [comment]
Yes.

**Comment by glebb** [comment]
Duh. I just wrote the endpoint wrong. Removing the first slash solved the problem. So "index.php?p=api/categories" did the trick.
