### ISSUE TITLE
404 not found on fresh installation

### ISSUE THREAD

**Issue by xDaizu** [kasperisager/vanilla-api#53]
Today I updated Vanilla to the most recent master release, installed the current master branch api and it throws a 404 on every request to {{vanilla}}/api. 

Maybe something's changed in the Vanilla router?

**Comment by kasperisager** [comment]
Possibly a duplicate of #28.

**Comment by xDaizu** [comment]
Not a duplicate, Im accessing the same URLs (with al its /users and all its parameters) as before the Vanilla update, through php scripts, POSTman and browser ;)

**Comment by kasperisager** [comment]
Closing this as an environment specific issue as I've not been able to replicate it at all.
