### ISSUE TITLE
User->add returns empty response (vanilla 2.2.x)

### ISSUE THREAD

**Issue by fgerards** [kasperisager/vanilla-api#54]
Hi,

when adding a user the forum/your API returns an empty array - in your endpoint wiki you state, that user,activities, roles arrays are returned. Without any info on the created user (id etc.) it is not possible to go on with some postProcessing in own controllers/applications.

Is this a bug in your API or a misbehaviour in the vanilla core ?

**Comment by kasperisager** [comment]
This would be an issue in Vanilla core as per the README:

> Vanilla API is a shim that implements a RESTful URI scheme upon with you can invoke different methods using the standard GET, POST, PUT and DELETE HTTP verbs. The API then translates and redirects your request to the corresponding application controller which in return caries out the requested method.

**Comment by ddouglas493** [comment]
Can this be revisited now that v2.3.1 is out?
