### ISSUE TITLE
User-add : set PhotoURL property

### ISSUE THREAD

**Issue by fgerards** [kasperisager/vanilla-api#55]
Hi,

is it possible to set the photourl property when adding a user ? in the Profile Object in the response of "find a user" the PhotoUrl/Photo prop is returned - but where can it be set ?

**Comment by kasperisager** [comment]
You'll have to check the corresponding Vanilla controller to see if this is possible. Form data is however not currently accepted in requests, so you'd have to find a way around that for now at least.
