### ISSUE TITLE
blank website

### ISSUE THREAD

**Issue by gregroiusairlangga** [kasperisager/vanilla-api#57]
Website become blank when i extract this plugin to /applications,
do you know how to fix that?

thankyou.

ps: i already rename file to "api" but it was not work

**Comment by kasperisager** [comment]
Which version of PHP is your server running?

**Comment by gregroiusairlangga** [comment]
hello, thankyou for your response
i use php 5.3.28
is this a problem?

**Comment by kasperisager** [comment]
That's the problem, yes: Vanilla API requires PHP 5.4 and above.

**Comment by gregroiusairlangga** [comment]
okay thankyou, i will try in php 5.4 :)
