### ISSUE TITLE
http://54.200.224.132/vanilla2/api/discussion/3 get Page Not Found 

### ISSUE THREAD

**Issue by keinyuan** [kasperisager/vanilla-api#58]
http://54.200.224.132/vanilla2/index.php?p=/discussion/3/ works fine.

My env: 
vanilla-2.1.11
pwd
 htdocs/vanilla2/applications/api
cd  api
git log
commit e027615840f6da08351e15319dcbf4d02105d0e7
Author: Kasper Isager <kasperisager@gmail.com>
Date:   Wed Aug 12 16:20:50 2015 +0200

    Fix formatting error.

Could you please help?

**Comment by kasperisager** [comment]
The endpoint you're trying to access doesn't exist. It should be `/api/discussions/3` as per the docs: https://github.com/kasperisager/vanilla-api/wiki/Endpoints#find-a-discussion

**Comment by keinyuan** [comment]
http://54.200.224.132/vanilla2/api/discussions/3/ give Page Not Found too.

**Comment by keinyuan** [comment]
Thanks Kasper! I tried http://54.200.224.132/vanilla2/api/discussions/3 but still not able to let it work.
