### ISSUE TITLE
 http://54.200.224.132/vanilla2/api/discussions/3 does not work

### ISSUE THREAD

**Issue by keinyuan** [kasperisager/vanilla-api#59]
the same issue as #58 
/api/discussions/3 
/api/discussions/2
does not work, give 404 error

**Comment by kasperisager** [comment]
Based on #58 it looks like you don't have any rewrite rules in place. You may want to take a look at https://github.com/kasperisager/vanilla-api/issues/50#issuecomment-102982665.

**Comment by keinyuan** [comment]
still no lucky, http://sharecarprice.com/vanilla2/index.php?p=api/categories  get 404

**Comment by kasperisager** [comment]
Did you enable the app in the dashboard?

**Comment by keinyuan** [comment]
yes I did .
Addon -> Applications 
API	Extensible RESTful API shim that operates in JSON or XML. Supports JSONP and CORS
Disable  Settings	Version 0.4.0|Requires: Vanilla Version 2.2.x|By Kasper Kronborg Isager|Visit Site

When click settings it will show:

API
Endpoint
0

Application Secret
0
0

then a text box with generated secret ( UUID?) followed by a Re-generate key.

Everytime I get to this page it shows a different secret.

**Comment by kasperisager** [comment]
Which version of Vanilla are you using?

**Comment by keinyuan** [comment]
https://github.com/vanilla/vanilla.git master branch
bitnami@ip-172-31-39-252:~/htdocs/vanilla2$ git remote -v
origin  https://github.com/vanilla/vanilla.git (fetch)
origin  https://github.com/vanilla/vanilla.git (push)
bitnami@ip-172-31-39-252:~/htdocs/vanilla2$ git branch
* master

**Comment by keinyuan** [comment]
I did some change and now get a different result:
According to https://github.com/kasperisager/vanilla-api/issues/50
you mentioned 
Everything's fine on my end on the latest master (vanilla/vanilla@054707a). Which endpoint are you trying to access?


so I checked out 054707a from master then git cloned api into applications/api  and did a fresh install. 

after this access http://sharecarprice.com/vanilla/api/discussions/1 give me:

Something has gone wrong.

We've run into a problem and are unable to handle this request right now. 
Please check back in a little while.

:(

**Comment by kasperisager** [comment]
Closing as an environment issue.
