### ISSUE TITLE
Installing API on Vanilla 2.1

### ISSUE THREAD

**Issue by sskohli** [kasperisager/vanilla-api#60]
Hi,
The client has Vanilla 2.1, They don't want to upgrade to 2.2 yet.
I tried enabling the API Application, but I get an error "Success"
I think it should be just disabling some output.

<img width="639" alt="screen shot 2015-08-30 at 11 55 26 am" src="https://cloud.githubusercontent.com/assets/3405067/9565988/40c0e7b4-4f0e-11e5-8fed-43a1d3c9683f.png">

**Comment by kasperisager** [comment]
The API app is not compatible with Vanilla 2.1 as it relies on features introduced in 2.2.

**Comment by sskohli** [comment]
hmm allright! will let the client know.
Thanks
