### ISSUE TITLE
Paginated response i.e. for /api/users

### ISSUE THREAD

**Issue by fgerards** [kasperisager/vanilla-api#62]
Hi,

we got 500+ Users in the forum.
When we create a user via the API, the response is empty. To get the freshly created user uid we have to query all users and search throught them by email-attribute. Problem: Vanilla Forum only responds 30 users out of 500+ by default - is there any way to disable this pagination or is there a limit inside vanilla configuration for API responses ?

**Comment by Jakub-Fajkus** [comment]
Hello, 
did you solve this issue?

**Comment by fgerards** [comment]
Hi, there is a page-GET param you can send through the API skim and paginate through the 30-items pages. I ended up modifying the vanilla-forum usercontroller-Action summary() and add the limit param there and in the vanilla-api, so i can pass a limit GET Param to the /users/summary endpoint

**Comment by kasperisager** [comment]
The API is only a shim for built-in controller methods so using the `Page` param would be the way to go.
