### ISSUE TITLE
Is there any way to flag message as read?

### ISSUE THREAD

**Issue by Jakub-Fajkus** [kasperisager/vanilla-api#63]
Hi, 
I'm implementing chatting system API for our mobile app and I have found that I need to flag message as read. I didn't find any way in the doc. Is there any hidden way to do that?

**Comment by kasperisager** [comment]
No controller methods exists for this as it happens automagically on page fetches. It's therefore not something that the API app can shim.

**Comment by Jakub-Fajkus** [comment]
It is really done automatically. Shame on me. I haven't noticed that. But thank you for yours reply.

**Comment by kasperisager** [comment]
No problem, glad to be of help!

**Comment by JamesMercury** [comment]
@Jakub-Fajkus hi there! How did you authenticate users in your mobile app?

**Comment by Jakub-Fajkus** [comment]
Hi. Well, i don't have the access to the code now. But as I remember we had a website with OAuth server. Mobile app was authenticating to the server with access token. And the website was kind of a proxy to the vanilla API. So when the mobile app requested something from the forum, the mobile app had to call the website API and the website called the vanilla API(authenticating with the API key,  I think).
