### ISSUE TITLE
Authentication via User Password 

### ISSUE THREAD

**Issue by JamesMercury** [kasperisager/vanilla-api#65]
Hello Kasper,

I've built an external app using your API that's working great. But I have it working in such a way that users authenticate with their usernames & emails as these are the parameters required for secure endpoints. 

Please point me in the write direction to authenticating via password. Thanks.

**Comment by kasperisager** [comment]
Hi! This should hopefully be of help: https://github.com/kasperisager/vanilla-api/wiki/Authentication#session-based

**Comment by JamesMercury** [comment]
This option seems to be for web based apps. 
I'm using the api for an android(Cordova actually) app. Would session based authentication still work?

**Comment by kasperisager** [comment]
JsConnect would currently be the only solution in cases where key authentication is insufficient.
