### ISSUE TITLE
no discussion id on comment object after /search api call

### ISSUE THREAD

**Issue by sadlands** [kasperisager/vanilla-api#66]
Hi there!

I was wondering whether you could add the corresponding discussion identifier to elements with "RecordType: Comment" after performing a search api call. It already has references to the user who wrote it and the category it was posted in, but I dont see any ways of finding the ID of the actual discussion, which is what I would need :) Thank you very much for considering my request, Happy Festivus and Merry Christmas to you and your family!

Best,
Marc

**Comment by kasperisager** [comment]
Since the API application is simply a shim layer, it doesn't in any way control the output. You'd have to direct your request to Vanilla core instead.
