### ISSUE TITLE
Something has gone wrong

### ISSUE THREAD

**Issue by eddieSullivan** [kasperisager/vanilla-api#69]
Every endpoint gives this error:

Something has gone wrong.

We've run into a problem and are unable to handle this request right now.
Please check back in a little while.

**Comment by kasperisager** [comment]
You will have to enable debug mode to figure out what's going on.

**Comment by eddieSullivan** [comment]
I saw the error on the latest Github code, but it went away when I went back to the released version. Sorry I don't have more information to offer on what the issue was.
