### ISSUE TITLE
URLs are missing scheme

### ISSUE THREAD

**Issue by odrobnik** [kasperisager/vanilla-api#71]
I noticed when querying the categories the URL property is missing the scheme.

`Url = "//www.server.com/_dev/categories/general";`

The same is true for `LastUrl`:

`LastUrl = "//www.server.com/_dev/discussion/1/bam-you-ve-got-a-sweet-forum#latest";`

We believe that the same scheme that you are accessing the API with should be returned here.

**Comment by kasperisager** [comment]
The API is simply a proxy to the internal controller methods, so this issue should be reported in Vanilla core.

**Comment by odrobnik** [comment]
@kasperisager Would you mind doing that, as you are the one that knows which parts of Vanilla core you are accessing?

**Comment by kasperisager** [comment]
The extent of my knowledge with regards to the API is "a method with this name in this controller" so I've honestly no idea what the issue might be. Could you try accessing `/categories.json` to see if the schemes are missing from that output as well?

**Comment by odrobnik** [comment]
Yes, `categories.json` also returns the URLs without scheme.

**Comment by kasperisager** [comment]
Then the issue lies in either your setup or Vanilla core. I get the correct URLs when accessing that endpoint both directly and through the API.
