### ISSUE TITLE
Method not allowed when fetching User

### ISSUE THREAD

**Issue by lww** [kasperisager/vanilla-api#73]
The documentation states that I can fetch a user with `/api/users/:id` (Authentication optional).

Unfortunately I get an Error 404 when I make this request:

GET http://www.myserver.com/api/users/1
{
  "Code" : 405,
  "Exception" : "Method Not Allowed"
}

Any advice?

**Comment by kasperisager** [comment]
Do the other endpoints work as expected?

**Comment by lww** [comment]
Yes, everything else works fine...

**Comment by kasperisager** [comment]
Seems odd then... Could you paste the output of [this variable](https://github.com/kasperisager/vanilla-api/blob/master/library/class.apiengine.php#L81) when accessing the endpoint in question? Either by a breakpoint or a simple `exit($requestMethod);`

**Comment by lww** [comment]
I currently have no access to the server. I'll tell you on Monday. Thanks!

**Comment by kasperisager** [comment]
Any word on this?

**Comment by lww** [comment]
I've decided to write my own, so I haven't investigated the issue any further. But thank you for your time!

**Comment by kasperisager** [comment]
No worries!
