### ISSUE TITLE
Not able to access /api

### ISSUE THREAD

**Issue by pn279j** [kasperisager/vanilla-api#74]
I installed vanilla forums in my Windows machine. I am using wamp server with php v 5.4. I installed vanilla-api as an application and renamed it api . I am not able to access the API using /api endpoint. Any idea what might be the issue?

**Comment by kasperisager** [comment]
There's nothing to be found at the API root. You can find a list of available endpoints here: https://github.com/kasperisager/vanilla-api/wiki/Endpoints

**Comment by pn279j** [comment]
Thanks Kasper! I was able to access the endpoints now! But while creating a user(/api/users), I am getting an error ""You must select at least one role."" . My request seems to be ok. I am giving role id as 8 so that the user can be created with "Member" role
{
  "Name": "ae_test",
  "Email": "ae_test@att.com",
  "Password": "password123",
  "RoleID": 8
}

Any idea why this is happening?

**Comment by kasperisager** [comment]
No problem! As can be seen in the endpoint docs, `RoleID` should be an array: https://github.com/kasperisager/vanilla-api/wiki/Endpoints#create-a-new-user

**Comment by pn279j** [comment]
Got it! It gives me this error now:
{
  "Code": 400,
  "Exception": "Could not instantiate mail function."
}

I dont want to set up an email functionality to notify the user. It just want the user to be created silently.

**Comment by kasperisager** [comment]
Vanilla will try sending a mail regardless, and if no external mail provider is configured it will attempt using a built-in; in your case it seem there's none.

**Comment by pn279j** [comment]
I see. 
I am this close to locking your Api to use in our application. Couple of more questions. thanks for your patience in advance!
1. I could create a user successfully. I am trying to insert a comment on behalf of the user.My endpoint is: /api/discussions/1/comments?username=ae_test&timestamp=1466280869&token=55df6761443627119c16ded21fa9ae865a6628ff8ffb37c53a1a6b352b55de65
It seems to insert the comment but on behalf of the admin (vanilla-admin) and not the user I am sending as a parameter (ae_test)
2. I was able to create a comment without sending any authentication (/api/discussions/1/comments), i.e without sending the HMAC token. In the documentation, it says that create comment api needs authentication.

Again, thanks for your support.

**Comment by pn279j** [comment]
Hi again!
You can ignore my last message. I already had a logged in session for vanilla-admin, so it created the comment on behalf of that. I logged out and I get this error now while trying to create a comment:
PHP Fatal error:  Call to a member function firstRow() on a non-object in C:\\Apache\\Apache2.2\\htdocs\\vanilla\\applications\\vanilla\\controllers\\class.postcontroller.php on line 779
URL:

**Comment by pn279j** [comment]
I have another question, can I get the number of views for a particular discussion? Thanks!

**Comment by pn279j** [comment]
Hi Kasper! We have been able to make all of the features work with your api. Very impressive work. However, we were wondering if "liking" a comment or discussion is supported in your API. Thanks in advance!

**Comment by pn279j** [comment]
Also, can we extend the API to upload images/videos for comments/discussions?

**Comment by kasperisager** [comment]
"Liking" as in [YAGA](https://vanillaforums.org/addon/yaga-application)? Either way, you can absolutely extend the API with mappings for any controller methods: https://github.com/kasperisager/vanilla-api/wiki/Extending

The API currently only supports JSON bodies, so controller methods that require form data (like uploads) however aren't supported.

**Comment by pn279j** [comment]
Thanks Kasper.
I am trying to update a discussion by calling PUT on /discussions/{id} and it is coming back with a 400 Bad Requuest. Here is my request:
{
  "CountViews": "14"
}

I am sending application/json in the headers and also sending the token as part of authentication.
URL: {{domain}}/api/discussions/36?username={{username}}&timestamp={{timestamp}}&token={{token}}

Any idea why this is happening?
i want to increment the number of views of a discussion everytime it is clicked, hence the reason for updating the discussion.

**Comment by kasperisager** [comment]
You can only specify the parameters outlined in the documentation: https://github.com/kasperisager/vanilla-api/wiki/Endpoints#update-a-discussion

**Comment by pn279j** [comment]
Thanks! I have another question. I am trying to get a user by its id using GET /api/users/{id} and it comes back with User not found. I am very sure that the id I am passing in the parameter is a valid user id. Any idea why this is happening?

**Comment by kasperisager** [comment]
How does the entire request look?

**Comment by pn279j** [comment]
Here is the curl:
curl -X GET -H "Accept: {{accept}}" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: a218dc51-5544-c720-3179-1734696b4fba" "<our server name>/vanilla/api/users/2"

User id 2 exists because i was able to get it as part of /users call. Below is the snippet from /users response:
{
      "UserID": "2",
      "Name": "vanilla-admin",
      "Photo": null,
      "Title": null,
      "Location": null,
      "About": null,
      "Email": "***********",
      "ShowEmail": "0",
      "Gender": "u",
      "CountVisits": "6",
      "CountInvitations": "0",
      "CountNotifications": "0",
      "InviteUserID": null,
      "DiscoveryText": null,
      "Preferences": {
        "ShowAllCategories": true
      },
      "DateSetInvitations": null,
      "DateOfBirth": "1975-09-16 00:00:00",
      "DateFirstVisit": "2016-06-09 19:03:00",
      "DateLastActive": "2016-06-24 19:09:31",
      "LastIPAddress": "135.70.46.12",
      "AllIPAddresses": "135.70.46.12,135.28.59.142,135.161.238.86,130.10.39.183,135.28.59.141,135.28.59.143,135.70.47.21",
      "DateInserted": "2016-06-09 19:03:00",
      "InsertIPAddress": "135.28.59.142",
      "DateUpdated": "2016-06-09 19:03:00",
      "UpdateIPAddress": null,

**Comment by kasperisager** [comment]
Nothing odd going on... Have you tried making the request authenticated?

**Comment by pn279j** [comment]
It works with the request authenticated. The documentation says that the authentication is optional. Anyhow, I have it working now and am not blocked. Thanks again!!

**Comment by pn279j** [comment]
Hi,

while creating a new discussion, I am getting the following exception: 
{"Code":256,"Exception":"","Class":"Gdn_ErrorException"}

Here is my request:
{
  "Name": "New Post from postman",
  "Body": "Body for new post",
  "CategoryID": 3
}

any idea why this exception occurs?
thanks in advance.

**Comment by kasperisager** [comment]
Are you still experiencing this issue and if so could you open up a new issue? Thanks!
