### ISSUE TITLE
Registering a new user -> response missing

### ISSUE THREAD

**Issue by SwissDeadCow** [kasperisager/vanilla-api#75]
Unfortunately, the response, when registering a new user, is blank; it's not as you wrote in the endpoint description.
Becoming the new userid as response would be great.

**Comment by kasperisager** [comment]
The API application unfortunately has no control over neither the endpoint input nor output; it's merely a shim layer on top of the builtin controllers. What you're describing could however be a regression in Vanilla core, but I could also be wrong in terms of what the user controller returns. I do remember it returning the created user object, but this may never have been the case.

**Comment by SwissDeadCow** [comment]
Okay I understand. I changed the error handling according to the "new" response.
After a new user registration, I get the user id through an extra query and I save the data now in combination with email in a new table. Too bad I have to do this... Its taking additional time.
