### ISSUE TITLE
Page Not Found on Vanilla 2.3

### ISSUE THREAD

**Issue by Swennet** [kasperisager/vanilla-api#76]
I'm receiving a Page Not Found error when trying to access the API through any of the URLs.

For example: `https://mysite.com/community/api/discussions` returns a Page not Found error.

I noticed others have had the same issue pre-2.3, which were never solved. But I'm reporting here anyway in hopes to find a solution.

Specs: Ubuntu 16.04 with PHP 7 and Apache2

**Comment by Swennet** [comment]
**Update:** I installed 2.2.1 on a test server to see if it was strictly related to Vanilla 2.3, and that seems to be the case. I can access the API perfectly fine on Vanilla 2.2.1, but not on 2.3.

Any chance of the application being updated?

**Comment by kasperisager** [comment]
I can verify that the application is indeed incompatible with Vanilla 2.3 😞 Help would however be greatly appreciated in that regard as I don't have time to work on this myself.

**Comment by Swennet** [comment]
I would like to help but honestly, I have no idea where to start and my understanding of Vanilla and API functions is very limited. Any ideas on what could have caused this incompatibility?

**Comment by kasperisager** [comment]
Had a moment to look at this today and found that the Garden autoloader is borked. I've therefore switched to using the Composer autoloader which correctly resolves the bundled APIs.

**Comment by VeeK727** [comment]
I've downloaded the 0.5 release and it still shows the same problem. Is it fixed for others?

**Comment by kasperisager** [comment]
Works fine on my end. Have you tested it on 2.2 to verify that it's not an environment specific problem?

**Comment by VeeK727** [comment]
No I haven't. I'll install a 2.2 setup and let you know

**Comment by VeeK727** [comment]
It's working fine. I actually missed the part that says "make sure the newly created folder is named api and not vanilla-api". Had to rename the folder. Thanks

**Comment by kasperisager** [comment]
Ah, perfect!
