### ISSUE TITLE
Get most popular discussions?

### ISSUE THREAD

**Issue by VeeK727** [kasperisager/vanilla-api#79]
Is it possible to use the api to get n number of most popular discussions from the forum? By popular I mean the ones with most views or comments.

**Comment by kasperisager** [comment]
AFAIK this isn't supported in Vanilla out of the box and as such isn't supported by the API shim either. You can however always create the method yourself and map it to an API endpoint: https://github.com/kasperisager/vanilla-api/wiki/Extending
