### ISSUE TITLE
Extending

### ISSUE THREAD

**Issue by isaac-perkins** [kasperisager/vanilla-api#82]
Hey,

I need to be able to get at media that's attached to Discussions. 

It occurred to me that this might be pretty common, anyone?

Otherwise - how would I go about it?

**Comment by kasperisager** [comment]
You might be interested in this: https://github.com/kasperisager/vanilla-api/wiki/Extending

**Comment by isaac-perkins** [comment]
Oh, sorry. Didn't see the wiki.

I had a really quick glance through the source, you like mapping these calls to their classes yeh? Doesn't work so well for media as they don't have one for that...

**Comment by kasperisager** [comment]
In that case you would need to first create a controller with an associated method that does what you need; you can then map this method to an endpoint in the API.

**Comment by isaac-perkins** [comment]
yep. ok. Thanks.
