### ISSUE TITLE
Create new accounts on vanilla

### ISSUE THREAD

**Issue by neexs** [kasperisager/vanilla-api#83]
Hi,

I actually have a webpage where I store informations about users (using session variables). On that website, I embedded my vanilla forum. 

The thing that I want is when they access the page on my website where there's the embedded forum, it creates them an account automatically with their informations.

So I've found your API which is really nice. I started testing it with endpoints which don't require authentication (discussions, categories...). Then I tried to authenticate to be able to use the rest of the methods of the API but I'm always getting this exception : 

```
{
  "Code": 401,
  "Exception": "Authentication required for this endpoint"
}

```

or other exceptions telling me I'm not autorized.

I'm testing all that using postman and/or ajax.

I assume that I don't really understand how to authenticate via the API. Any suggestions and examples about that ? 

Thanks

**Comment by kasperisager** [comment]
You can find documentation on authentication here: https://github.com/kasperisager/vanilla-api/wiki/Authentication

**Comment by neexs** [comment]
I've already followed the steps but I think I don't get how to add a user. 

That's my postman interface :
![1](https://cloud.githubusercontent.com/assets/12820536/24140290/bd6a6886-0e1f-11e7-8c09-849d55725207.jpg)

That's how I generate my token (hash)  and timestamp (test environment) : 

![2](https://cloud.githubusercontent.com/assets/12820536/24140407/35ca99fe-0e20-11e7-8784-ce68cc93ab51.PNG)

When I replace RoleID by an array like 
`array(8) ` or `[8]`
I get an error in my php saying that i can't convert array to string.

Am I doing it wrong  ?

**Comment by neexs** [comment]
Requets : 

```
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL,            "http://MYURL/forum/api/users?username=YYYY&timestamp=1490091072&token=96f96a3970a42a6b9a2d967bb7c090984df626de3c8ae612e31aa6877621830a" );
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1 );
curl_setopt($ch, CURLOPT_POSTFIELDS,     '{"username":"XXXX","name":"test","email":"test@yahoo.fr","password":"test","roleid":"[8]","timestamp":1490090298}' ); 
curl_setopt($ch, CURLOPT_HTTPHEADER,     array('Content-Type: application/json', 'Accept: application/json')); 

$result=curl_exec ($ch);

echo $result;
```

Response :
`
{ "Code": 400, "Exception": "You must select at least one role. Name is required. Password is required. Email is required." }`

**Comment by neexs** [comment]
Ok my problem is that I can't pos data. I can only retrieve them with the get method. For example, I can get all users, all roles etc but can't add one.

**Comment by kasperisager** [comment]
Token generation looks fine 👌 As for the endpoint parameters, those have to be provided in the request body: https://github.com/kasperisager/vanilla-api/wiki/Endpoints#create-a-new-role. The parameters passed in the query string are typically only used for authentication.

**Comment by neexs** [comment]
Oh okay I see now. Thanks ! So authentication params are passed by url and informations we want to retrieve are send by post params.

So here's my code which is working  (for people that are maybe facing some issues like me)  :

```
<?php 

/* Informations sur l'authentification */

$timestamp = time(); 
$username = "your_admin_username"; 
$method = array("users","configuration","roles"); //discussions, etc ...

$request_authentication = array(
	'username' => $username, 
	'timestamp' => $timestamp);

ksort($request_authentication);
$request_authentication = implode('-', $request_authentication);
$secret_code = '149bd9f4-aac6-4ab2-bcb7-ec5e1b574360';
$token = hash_hmac('sha256', strtolower($request_authentication), $secret_code);
$data = array('Name'=>'Test',
              'Email'=>'test@mail.fr',
              'Password'=>'pass',
              'RoleID'=> [8]);
$header = array('Content-Type: application/json',
				 'Accept: application/json');

/* Construction de l'URL */
$url = "http://YOURURL/forum/api/".$method[0]."?username=$username&timestamp=$timestamp&token=$token" ;

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt($ch, CURLOPT_POST, count($data) );
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data) ); 
curl_setopt($ch, CURLOPT_HTTPHEADER, $header); 
$result=curl_exec ($ch);

echo $result;
```

**Comment by kasperisager** [comment]
No problem, glad to hear that it worked out!
