### ISSUE TITLE
405 Method not allowed for categories endpoint

### ISSUE THREAD

**Issue by HIAviator** [kasperisager/vanilla-api#84]
I'm pulling discussions successfully but when I attempt to pull a list of category discussions such as:

/api/categories/general-gaming

I get a 405 "Method not allowed" error.

Looking at the class.categoriesapi.php file it should be possible according to:

static::get("/[i:CategoryIdentifier]", [
     "controller" => "Categories"
]);

Any insight into what might be going on?

**Comment by HIAviator** [comment]
I fixed this issue by updating the match type from:

static::get("/[i:CategoryIdentifier]", [
"controller" => "Categories"
]);

to:

static::get("/[*:CategoryIdentifier]", [
"controller" => "Categories"
]);

**Comment by kasperisager** [comment]
Good catch, thanks! I'll push a fix right away.
