### ISSUE TITLE
Update the addon from https://open.vanillaforums.com/

### ISSUE THREAD

**Issue by deinok** [kasperisager/vanilla-api#86]
https://open.vanillaforums.com/addon/api-application

The latests version dont work with vanilla 2.3.X update it please, because that version only gives 404 errors ;)

cc: @rsprat

**Comment by kasperisager** [comment]
Changes to the addon directory prevent me from uploading new versions of the API application, so I've stopped updating it. You can find the latest release here though: https://github.com/kasperisager/vanilla-api/releases

**Comment by deinok** [comment]
Okey, closing this ;)
